[package]
name = "toy-chain"
version = "0.1.0"
edition = "2024"

[dependencies]
rpc-server = {path = "../../crates/rpc-server"}
tokio.workspace = true
anyhow.workspace = true
clap.workspace = true
toml.workspace = true
config_rs.workspace = true
config.workspace = true